[project]
name = "zotero-cli"
version = "0.2.0"
description = "A tool to add papers from various sources (arXiv, BibTeX) to Zotero"
authors = [{name = "FÃ¡bio Chicout", email = "fchicout@gmail.com"}]
requires-python = ">=3.8"
dependencies = [
    "requests",
    "beautifulsoup4",
    "feedparser",
    "bibtexparser",
    "arxiv",
    "rispy"
]

[project.scripts]
zotero-cli = "paper2zotero.cli.main:main"

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["src"]

