[project]
name = "zotero-cli"
version = "1.0.7"
description = "A CLI tool to import research papers into Zotero from arXiv, BibTeX, RIS, and CSV."
authors = [{name = "FÃ¡bio Chicout", email = "fchicout@gmail.com"}]
readme = "README.md"
requires-python = ">=3.8"
license = {file = "LICENSE"}
keywords = ["zotero", "research", "arxiv", "bibtex", "ris", "cli", "automation"]
classifiers = [
    "Development Status :: 4 - Beta",
    "Environment :: Console",
    "Intended Audience :: Science/Research",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Topic :: Scientific/Engineering",
    "Topic :: Utilities"
]
dependencies = [
    "requests",
    "beautifulsoup4",
    "feedparser",
    "bibtexparser",
    "arxiv",
    "rispy",
    "rich",
    "mermaid-py"
]

[project.urls]
Repository = "https://github.com/fchicout/zotero-cli"
Issues = "https://github.com/fchicout/zotero-cli/issues"

[project.optional-dependencies]
dev = [
    "coverage",
    "pytest",
    "pytest-cov"
]

[project.scripts]
zotero-cli = "zotero_cli.cli.main:main"

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["src"]