[project]
name = "arxiv2zotero"
version = "0.1.0"
description = "A tool to add arXiv query results to Zotero"
authors = [{name = "FÃ¡bio Chicout", email = "fchicout@gmail.com"}]
requires-python = ">=3.8"
dependencies = [
    "requests",
    "beautifulsoup4",
    "feedparser",
    "bibtexparser"
]
[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["src"]

